future: true
name: Radek
auto: false
baseurl: /jekyll-blog
sass:
  style: compact # possible values: nested expanded compact compressed
exclude:
  - regen
  - sample-content
  - initialize-content.rb
  - README.md
plugins:
  - jekyll-kentico
  - jekyll-redirect-from
permalink: /:collection/:name
kentico:
  project_id: ENV_PROJECT_ID
  secure_key: ENV_DELIVERY_API_KEY
  front_matter_resolver: FrontMatterResolver
  content_resolver: ContentResolver
  filename_resolver: FilenameResolver
  data_resolver: DataResolver
  content_link_resolver: ContentLinkResolver
  inline_content_item_resolver: InlineContentItemResolver
  custom_site_processor: CustomSiteProcessor
  max_linked_items_depth: 5
  default_layout: default
  languages:
    - en-US
  posts:
    type: blog_post
    date: published
    tags: post_tags
    categories: post_categories
  pages:
    home:
    page:
    author:
      title: name
      collection: authors
  taxonomies:
   - sitemap
   - post_categories
   - post_tags